language: python
dist: xenial
sudo: true
python:
  - '3.7'
  - '3.8'
  - '3.9'
install:
    - pip install poetry
    - poetry install
script:
    - python -m pytest
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PW
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true